### ISSUE TITLE
Binding issue causing Android app to freeze/crash

### ISSUE THREAD

**Issue by amirvenus** [roubachof/Sharpnado.Presentation.Forms#16]
**Platform (please complete the following information):**
 - OS: [Android]
 - Device: [Samsung Galaxy/AndroidEmulator]

**Describe the bug**

Problem with binding when an observablecollection is being updated. 

**To Reproduce**

Here is my XAML:

```
      <renderedViews:HorizontalListView IsVisible="{Binding IsDoneGettingProds}"
                                                      Margin="0, 0, 0, -30"
                                                      VerticalOptions="End"
                                                      CollectionPadding="0,1"
                                                      ItemSpacing="5"
                                                      ItemHeight="244"
                                                      ItemWidth="134"
                                                      SnapStyle="Center" x:Name="rendView">
                        <renderedViews:HorizontalListView.ItemTemplate>
                            <DataTemplate>
                                <ViewCell>
                      
                                       <StackLayout>
                                           <Frame BorderColor="Beige" CornerRadius="2">
                                        <Grid>
                                            <Grid.RowDefinitions>
                                                <RowDefinition Height="70*" />
                                                <RowDefinition Height="15*" />
                                                <RowDefinition Height="15*" />
                                            </Grid.RowDefinitions>
                                   
                                            <Image
                                                Grid.Row="0"
                                               HeightRequest="85"
                                                WidthRequest="85"
                                                Source="{Binding image}"/>
                                          
                                            <Label
                                                Grid.Row="1"
                                                HorizontalOptions="CenterAndExpand"
                                                Text="{Binding ActualPrice, StringFormat='£{0:F}'}"
                                                FontSize="Small" />
                                        </Grid>
                                           </Frame>
                                    </StackLayout>
                                 
                                </ViewCell>
                            </DataTemplate>
                        </renderedViews:HorizontalListView.ItemTemplate>
                    </renderedViews:HorizontalListView>

```

And in App.xaml.cs inside the async OnStart method I am getting products using Task.WhenAll.

Inside Home.xaml.cs (where the XAML above is) I have the following inside OnAppearing():

```
    protected  override async void OnAppearing()
           {
               base.OnAppearing();

               while (!ZZZ.Instance.IsDoneGettingProds)
               {
                   await Task.Delay(100);
               }

            if(ZZZ.Instance.IsDoneGettingProds)
               rendView.ItemsSource = ZZZ.Instance.TopSelling;

        }

```

So I get loads of messages on the Console and the application freezes and crashes:
[0:] Binding: 'image' property not found on 'VanXApp.ZZZ', target property: 'Xamarin.Forms.Image.Source'
[0:] Binding: 'ActualPrice' property not found on 'VanXApp.ZZZ', target property: 'Xamarin.Forms.Label.Text'
[0:] Binding: 'image' property not found on 'VanXApp.ZZZ', target property: 'Xamarin.Forms.Image.Source'
[0:] Binding: 'ActualPrice' property not found on 'VanXApp.ZZZ', target property: 'Xamarin.Forms.Label.Text'
[0:] Binding: 'image' property not found on 'VanXApp.ZZZ', target property: 'Xamarin.Forms.Image.Source'

it only happens in Android and the iOS works perfectly fine.

**Comment by amirvenus** [comment]
When the app crashes it throws this error:

`01-02 14:43:05.171 I/art     (31642): Alloc concurrent mark sweep GC freed 7(264B) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 279us total 21.178ms
01-02 14:43:05.171 W/art     (31642): Throwing OutOfMemoryError "Failed to allocate a 1690012 byte allocation with 286560 free bytes and 279KB until OOM"
[0:] ImageRenderer: Error loading image: Java.Lang.OutOfMemoryError: Failed to allocate a 1690012 byte allocation with 286560 free bytes and 279KB until OOM
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <42dc777b518744fdae9988e94489a4a0>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <42dc777b518744fdae9988e94489a4a0>:0 
  at Android.Graphics.BitmapFactory.DecodeStream (System.IO.Stream is) [0x00029] in <1219ce5aae934ab095dc0e05b2110050>:0 
  at Android.Graphics.BitmapFactory+<>c__DisplayClass31_0.<DecodeStreamAsync>b__0 () [0x00000] in <1219ce5aae934ab095dc0e05b2110050>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.Forms.Platform.Android.ImageLoaderSourceHandler+<LoadImageAsync>d__0.MoveNext () [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ImageLoaderSourceHandler.cs:19 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.Forms.Platform.Android.ImageViewExtensions+<UpdateBitmap>d__2.MoveNext () [0x001a3] in D:\a\1\s\Xamarin.Forms.Platform.Android\Extensions\ImageViewExtensions.cs:57 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.Forms.Platform.Android.ImageRenderer+<UpdateBitmap>d__10.MoveNext () [0x00059] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ImageRenderer.cs:114 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.Forms.Platform.Android.ImageRenderer+<TryUpdateBitmap>d__9.MoveNext () [0x00026] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ImageRenderer.cs:95 
  --- End of managed Java.Lang.OutOfMemoryError stack trace ---
java.lang.OutOfMemoryError: Failed to allocate a 1690012 byte allocation with 286560 free bytes and 279KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:726)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:702)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:740)
01-02 14:43:05.492 D/ViewRootImpl@4e446dd[MainActivity](31642): ViewPostImeInputStage processPointer 0
01-02 14:43:05.597 D/ViewRootImpl@4e446dd[MainActivity](31642): ViewPostImeInputStage processPointer 1
01-02 14:43:06.192 D/ViewRootImpl@4e446dd[MainActivity](31642): ViewPostImeInputStage processPointer 0
01-02 14:43:06.753 D/ViewRootImpl@4e446dd[MainActivity](31642): ViewPostImeInputStage processPointer 1
01-02 14:43:09.864 D/ViewRootImpl@4e446dd[MainActivity](31642): ViewPostImeInputStage processPointer 0
01-02 14:43:10.519 D/ViewRootImpl@4e446dd[MainActivity](31642): ViewPostImeInputStage processPointer 1
`

**Comment by roubachof** [comment]
man, come one :)

```
Alloc concurrent mark sweep GC freed 7(264B) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 279us total 21.178ms 01-02 14:43:05.171 W/art (31642): Throwing OutOfMemoryError "Failed to allocate a 1690012 byte allocation with 286560 free bytes and 279KB until OOM" [0:] ImageRenderer: Error loading image: Java.Lang.OutOfMemoryError:
```

Do you really think it has something to do with binding ?

```
ImageRenderer: Error loading image: Java.Lang.OutOfMemoryError
```

**Comment by amirvenus** [comment]
Sorry but I am only a beginner in XF. 

The issue only happens in Android and not on iOS. 

The reason I got suspected about the binding is that it complains that:

[0:] Binding: 'ActualPrice' property not found on 'VanXApp.ZZZ', target property: 'Xamarin.Forms.Label.Text'
[0:] Binding: 'image' property not found on 'VanXApp.ZZZ', target property: 'Xamarin.Forms.Image.Source'

**Comment by roubachof** [comment]
It is not related with my library.
If you read carefully the exception you will understand that the problem come from the images you are loading. Probably a caching problem combined with too big images. You should use FFImageLoading library it will help you with that.

**Comment by amirvenus** [comment]
For the benefit of others, I managed to fix this issue by setting the largeHeap to true inside AndroidManifest.xml and limited number of items in the ObservableCollection to 20 on Android as clearly it was not capable of loading 600 items and now it works fine without crashing.

I also replaced Image with FFImage just in case. 

By the way, is there something like Caching strategy like https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/listview/performance ?

**Comment by roubachof** [comment]
Yes views are recycled.
